version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: goods_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  nats:
    image: nats:2
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"

  clickhouse:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    ports:
      - "9000:9000"     
      - "8123:8123"    
    volumes:
      - ch_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - nats
      - clickhouse

  consumer:
    build:
      context: .
      dockerfile: build/Dockerfile.consumer
    container_name: log-consumer
    depends_on:
      - nats
      - clickhouse

volumes:
  pgdata:
  ch_data:
